### ISSUE TITLE
Recipe "default" in v2.2.1 failed to run on CentOS 6.6

### ISSUE THREAD

**Issue by legal90** [atomic-penguin/cookbook-nfs#61] opened 2015-07-01 13:41 UTC
I can not figure out what really happens, but I suppose that it is due to `provider Chef::Resource::Service`:
```
================================================================================
           Error executing action `start` on resource 'service[portmap]'
           ================================================================================

           ArgumentError
           -------------
           wrong number of arguments (0 for 1..3)

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nfs/recipes/_common.rb

            43:   service component do
            44:     service_name node['nfs']['service'][component]
            45:     pattern node['nfs']['service'][component]
            46:     provider node['nfs']['service_provider'][component]
            47:     action [:start, :enable]
            48:     supports :status => true
            49:   end
            50: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nfs/recipes/_common.rb:43:in `block in from_file'

           service("portmap") do
             provider Chef::Resource::Service
             action [:start, :enable]
             supports {:status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "rpcbind"
             pattern "rpcbind"
             declared_type :service
             cookbook_name "nfs"
             recipe_name "_common"
           end

       Running handlers:
       [2015-07-01T16:31:23+03:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-07-01T16:31:23+03:00] ERROR: Exception handlers complete
       Chef Client failed. 30 resources updated in 91.527318639 seconds
       [2015-07-01T16:31:24+03:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-07-01T16:31:24+03:00] ERROR: service[portmap] (nfs::_common line 43) had an error: ArgumentError: wrong number of arguments (0 for 1..3)
       [2015-07-01T16:31:24+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by legal90** [comment] 2015-07-01 13:56
I've just reproduced it on Centos 6.5 too.

**Comment by legal90** [comment] 2015-07-01 14:47
Rolling back to v2.2.0 can be a workaround for that issue, since it isn't reproducing there.

**Comment by sfiggins** [comment] 2015-07-01 15:53
For me it seems to also have something to do with my Chef version.  If I'm converging with 11 I don't have the problem, but using the most recent 12, I do.

**Comment by atomic-penguin** [comment] 2015-07-01 16:20
This is a dupe of #60, and I was well aware of the issue, and working on it internally.  I got caught up with a software release for work, and couldn't get a fix out until now.  We have tested the fix across Ubuntu and CentOS, and seems to be working better by forcing the service_provider overrides only on the Ubuntu platform.

**Closed by atomic-penguin** 2015-07-01 16:20 UTC
