### ISSUE TITLE
Cannot find a provider for service on redhat version 6.6

### ISSUE THREAD

**Issue by clydedacruz** [atomic-penguin/cookbook-nfs#60] opened 2015-07-01 06:12 UTC
Im getting the following recipe compile error:
 ERROR: Cannot find a provider for service on redhat version 6.6

caused by this line in attributes file

>> default['nfs']['service_provider']['lock'] = Chef::Platform.find_provider_for_node node, :service

**Comment by clydedacruz** [comment] 2015-07-01 06:20
Considering Il always be using RHEL6.6  could I hardcode the service providers in the attribute file as a temporary fix ?

**Comment by legal90** [comment] 2015-07-01 13:55
@clydedacruz What cookbook version are you using? I have the following error with 2.2.1: https://github.com/atomic-penguin/cookbook-nfs/issues/61

**Comment by clydedacruz** [comment] 2015-07-01 15:50
worked when I commented the parts that are used to explicitly specify the providers to be used for each service .

**Comment by atomic-penguin** [comment] 2015-07-01 16:35
This is a dupe of #58.  I released 2.2.2 to force the provider to Upstart, only on an Ubuntu platform.  On RedHat/CentOS, Chef just seems to do the right thing with my testing this fix internally.

**Closed by atomic-penguin** 2015-07-01 16:35 UTC

**Comment by clydedacruz** [comment] 2015-07-01 17:00
Thanks ☺ Shall check it out
