### ISSUE TITLE
Heads up - RHEL7.1 is broken here

### ISSUE THREAD

**Issue by jblaine** [atomic-penguin/cookbook-nfs#52] opened 2015-03-11 20:29 UTC
See https://bugzilla.redhat.com/show_bug.cgi?id=1159308

Chef failure that surfaces. Worked in RHEL 7.0:

```
---- Begin output of /sbin/chkconfig nfs-lock on ----
STDOUT: 
STDERR: Note: Forwarding request to 'systemctl enable nfs-lock.service'.
Failed to issue method call: No such file or directory
---- End output of /sbin/chkconfig nfs-lock on ----
```

**Comment by atomic-penguin** [comment] 2015-03-11 20:32
Is it an issue caused by the cookbook, or just an issue with RHEL?

**Comment by jblaine** [comment] 2015-03-11 20:40
It's an issue with RHEL 7.1 from what I can tell, but it causes the `nfs::default` recipe to fail on all RHEL 7.1 boxes.

So, no, it's not caused by the cookbook other than the cookbook does not yet have a workaround for it (none known by me yet) ;)

**Comment by notnmeyer** [comment] 2015-04-08 19:51
I think the issue is that the service to being using on 7.1 is `rpc-statd` and no longer `nfs-lock`. I'm pushing through some pain related to this now, if I get it sorted I'll send a PR.

**Comment by jblaine** [comment] 2015-04-09 13:05
rpc.statd is the state manager, but is not the locking service itself. There's a kernel thread, lockd, that runs to handle the actual locking. The RHEL 7 Storage Administration Guide says the following, which does not work for me, so I will open a RH case under our support contract. I'd like to request that we keep this GH issue open for now though, please?

-------------------------------------------------------

8.1.1. Required Services
-------------------------------

...
* nfslock : systemctl start nfslock.service activates a mandatory service that starts the appropriate RPC processes allowing NFS clients to lock files on the server
...

-------------------------------------------------------

**Comment by atomic-penguin** [comment] 2015-04-09 14:46
I won't close the issue until we have some resolution in RHEL 7.x.  Please keep us informed with what you find out @jblaine.

**Comment by notnmeyer** [comment] 2015-04-09 16:10
@jblaine Interesting. On fresh 7.1 machines nfs-lock just seems to be an alias to rpc-statd:

```
[root@server-centos-71 ~]# systemctl status nfs-lock
rpc-statd.service - NFS status monitor for NFSv2/3 locking.
   Loaded: loaded (/usr/lib/systemd/system/rpc-statd.service; static)
   Active: inactive (dead)
```

**Comment by joerocklin** [comment] 2015-04-13 14:24
It looks like `nfs-[client|server].target` are expected to be used in RHEL7.1/CentOS7.1

**Comment by david-richer-adsk** [comment] 2015-05-06 01:17
Just hit me in the face with a server with latest CentOS 7.x. Do you guys have any workaround?

**Comment by Kuckkuck** [comment] 2015-06-02 10:55
+1 for a fix. ;-)

**Comment by jblaine** [comment] 2015-06-02 13:46
This is still being investigated by RH (what happened, why, and what their ultimate final answer is). The RH bugzilla ID is 1211788 but it is blocked from being seen (internal).

They were given a link to this GH issue in the process.

**Comment by joerocklin** [comment] 2015-07-22 19:47
More heads up: We hit a dependency issue in the `nfs-client.target` systemd unit file which was causing long startup times and a bit of a race condition if we installed the `nfs::client` pieces and tried to perform a mount via nfs in rapid succession (in a wrapper recipe). Our fix is to add an extra dependency via `nfs-client.target.d` to force `rpcbind.service` to start.

The questions I have now are: is anyone else seeing this (I haven't tried to reproduce this in a test just yet), and if so: should we consider accounting for this in this cookbook?

**Comment by karcaw** [comment] 2015-11-10 00:17
i am getting this error still:
STDOUT: 
    STDERR: Job for rpc-statd.service failed. See 'systemctl status rpc-statd.service' and 'journalctl -xn' for details.
    mount.nfs: rpc.statd is not running but is required for remote locking.
    mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
    mount.nfs: an incorrect mount option was specified


on centos:
CentOS Linux release 7.1.1503 (Core)

if i run:
systemctl start rpcbind

everything completes fine.

**Comment by joerocklin** [comment] 2015-11-10 12:10
@karcaw thanks for that report - I think that's the same issue we were seeing. If I have time this week I'll merge the changes we made internally into the public project for wider comment.

**Comment by Stromweld** [comment] 2018-07-20 19:13
nfs::default works for us on centos 7.5

**Closed** 2018-08-24 20:02 UTC
